---
- hosts: linux
  become: true

  vars:
    - openldapserver: "192.168.56.111"
    - basedn: "dc=example,dc=com"
    - ldapacc: "cn=admin,dc=example,dc=com"
    - ldappass: "toor"
    
  roles:
    - openldap-packages-installation
  #  - openldap-configuration